### ISSUE TITLE
Fehler falls man CreateRandomCodeverifier() mit 128 Länge verwendet

### ISSUE THREAD

**Issue by fue-medatixx** [gematik/ref-erp-client-cs#1]
Hallo,

beim Ausprobieren bekommen wir Ablauffehler wenn man bei CreateRandomCodeverifier() die 128 Länge verwendet, statt der 60.
Warum ist das so? Lt. https://github.com/gematik/api-erp/blob/master/docs/authentisieren.adoc#ablauf-des-authentifizierungsprotokolls soll man 128 zufällige Zeichen für den CODE_VERIFIER verwenden.

Für ein Feedback wäre ich dankbar.

**Comment by bneidhold** [comment]
Base64Url.Encode(_random.GenerateSeed(60)) erzeugt aus 60 Random-Byte (nicht 60 Zeichen) 80 Zeichen aus dem Zeichenvorrat. Der entsprechende RFC sagt "with a minimum length of 43 characters
   and a maximum length of 128 characters".  Wenn man 128 Byte als Input verwendet kommt man deutlich über das Maximum von 128 Zeichen und bekommt eine Exception.

**Comment by fue-medatixx** [comment]
Ah ok. Vielen Dank für die Info.
