### ISSUE TITLE
Payload leer beim erzeugen der jwe

### ISSUE THREAD

**Issue by unrealguest** [gematik/ref-erp-client-cs#2]
Hallo,

ich bin leider festgeklebt bei der Stelle wo man durch JWT.Encode den "jwe" erstellen müsste. Der generierte Payload wird immer leer.

`var jwePayloadJson = new JObject { ["njwt"] = jws }.ToString(Formatting.None);`
`string jwe = JWT.Encode(jwePayloadJson, idpEncKeyPublic, JweAlgorithm.ECDH_ES, JweEncryption.A256GCM,
                settings: new JwtSettings().RegisterJwa(JweAlgorithm.ECDH_ES, new ExampleEcdhKeyManagement()),
                extraHeaders: new Dictionary<string, object> {
                    {"exp", exp},
                    {"cty", "NJWT"},
                });`

Der generierte Token sieht dann so aus: *Header*..*Signature* (Payload ist nirgendswo zu finden)

jwePayloadJson wird in Ordnung generiert.

Könnten Sie bitte mir ein bisschen weiterhelfen worauf das Problem liegen könnte?

**Comment by bneidhold** [comment]
bitte weiter oben im Code schauen, ob bei CardInfoType[] smcbs = GetKonnektorSMCBs(); -> SMCBs geliefert werden. Wenn nicht, ist das eigentliche Problem, dass das TITUS Zugangszertifikat nicht da ist (muss unter C:\work\ps_erp_aps_01.p12).

**Comment by unrealguest** [comment]
SMCB-s werden geliefert. ExternalAuthenticate erfolgt auch. 

Payload wäre:
[njwt.txt](https://github.com/gematik/ref-erp-client-cs/files/6768178/njwt.txt)

Das generiertes Token sieht dann so aus:
[njwtEmptyPayload.txt](https://github.com/gematik/ref-erp-client-cs/files/6768143/njwtEmptyPayload.txt)

Wenn ich das nach https://idp.erezept-instanz1.titus.ti-dienste.de/sign_response poste, kommt die Fehlermeldung - "Challenge is ungültig" zurück.

Header beim Request is auch (theoretisch richtig) gesetzt.

**Comment by unrealguest** [comment]
Hmm okay, das Problem war ein flasches "alg" Header in der Payload.

jetzt kommt aber "Der Request besitzt keine gültige Signatur".

Sollte ich in diesem Fall in die Richtung SMC-B signieren gucken? Hat was mit ExternalAuthenticate in diesem Fall nicht geklappt?

**Comment by bneidhold** [comment]
Für dieses github-Projekt bitte nur posten, wenn der Bsp-Code hier 1:1 gegen den eigenen Titus-Account Probleme macht. (ich gehe mal davon aus, dass dies läuft). Alle anderen Probleme (gegen einen eigenen Konnektor der RU oder nach Modifikationen usw.) bitte normal über das Ticketsystem  der Gematik https://gematik.atlassian.net/servicedesk laufen lassen.
